// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package domain is a generated GoMock package.
package domain

import (
	gomock "github.com/golang/mock/gomock"
)

// MockUserIF is a mock of UserIF interface.
type MockUserIF struct {
	ctrl     *gomock.Controller
	recorder *MockUserIFMockRecorder
}

// MockUserIFMockRecorder is the mock recorder for MockUserIF.
type MockUserIFMockRecorder struct {
	mock *MockUserIF
}

// NewMockUserIF creates a new mock instance.
func NewMockUserIF(ctrl *gomock.Controller) *MockUserIF {
	mock := &MockUserIF{ctrl: ctrl}
	mock.recorder = &MockUserIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIF) EXPECT() *MockUserIFMockRecorder {
	return m.recorder
}
