name: Task-Go
on: push

jobs: 
  build: 
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      # - name: Test
      #   run: sudo add-apt-repository ppa:longsleep/golang-backports
      # - name: Test2
      #   run: sudo apt update
      # - name: Go Download
      #   run: sudo apt install golang-1.18
      # - name: Go Version
      #   run: go version
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
          # cache: true
          # cache-dependency-path: go.sum
      - name: Go Version
        run: go version
      
      - name: master checkout
        uses: actions/checkout@main
