name: Task-Go
on: push

# env:
#   CURRENT_DB_USER: ${{secrets.CURRENT_DB_USER}}
#   CURRENT_DB_PW: ${{secrets.CURRENT_DB_PW}}
#   CURRENT_DB_HOST: ${{secrets.CURRENT_DB_HOST}}
#   CURRENT_DB_PORT: ${{secrets.CURRENT_DB_POST}}
#   CURRENT_DB_NAME: ${{secrets.CURRENT_DB_NAME}}

jobs: 
  build: 
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      # - name: Test
      #   run: sudo add-apt-repository ppa:longsleep/golang-backports
      # - name: Test2
      #   run: sudo apt update
      # - name: Go Download
      #   run: sudo apt install golang-1.18
      # - name: Go Version
      #   run: go version
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
          # cache: true
          # cache-dependency-path: go.sum
      - name: Go Version
        run: go version
      
      - name: Bracnk Checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
      
      - name: Go Build
        run: go build

      - name: Docker Compose Up
        run: docker-compose up -d
      # - name: Set Env
      #   run : export CURRENT_DB_USER=user CURRENT_DB_PW=passwd CURRENT_DB_HOST=localhost CURRENT_DB_PORT=5434 CURRENT_DB_NAME=user
      - name: Go Run TestCode
        run: go run ./migrate/migrate.go
        # ;go test -v ./...
        env:
          CURRENT_DB_USER: user
          CURRENT_DB_PW: passwd
          # CURRENT_DB_HOST: localhost
          CURRENT_DB_HOST: "127.0.0.1"
          CURRENT_DB_PORT: "5434"
          CURRENT_DB_NAME: user